# Negative Binomial Distribution

## Introduction

In this lesson, you'll learn about negative binomial trials, and the negative binomial distribution!

## Objectives

You will be able to:

* Understand and explain the Negative Binomial Distribution and its uses


## Negative Binomial Trials

To understand the Negative Binomial Distribution, we first need to have a clear understanding of what it describes--**_Negative Binomial Trials_**. This sounds more intimidating that it actually is--the idea is actually pretty straightforward.  

Consider the following question:

I have a fair coin.  Let's consider heads a success, and tails a failure.  How many times can I flip the coin before I fail 3 times?

The first thought you'll probably have is that there's no single answer to this--instead, the answer falls across a distribution of probabilities.  It's possible that our first three flips in are all tails.  It's also possible (but exceedingly unlikely) that we flip the coin 100 times (or 1,000, or 1,000,000 times) and not still have heads show up less than 3 times in total. 

The **_Negative Binomial Distribution_** allows us to easily describe the probability distribution of the different ways a Negative Binomial Trial could work out.  

In more formal terms, the Negative Binomial Distribution requires the following parameters:

The Negative Binomial Distribution describes the number of successes $ k $ until observing a pre-determined number of failures $ r $ where the probability of success for each independent trail is $ p $.  

Note that since there's no such thing as half a tails or half a trial,  this means that the Negative Binomial Distribution is a **_Discrete Distribution_**, since it's concerned with multiple discrete, independent events. 

#### Sucess or Failure?

Note that depending on where you look, you'll see some sources that define $r$ as a fixed number of **_failures_**, while others will describe it as a fixed number of **_success_**.  Don't be confused by this--both of these definitions just describe two sides of the same coin (pun intended).  By definition, any trial with a binary outcome can equally be described in terms of failure or success.  For instance, saying "What is the probability that it takes me 6 coin flips to get tails twice?", it doesn't actually matter if we define tails as a "success" or as a "failure"--all that matters is that we calculate the probability that tails makes its 2nd appearance on the 6th flip.    

For the sake of simplicity, we'll define $r$ as the fixed number of **_failures_** throughout this lesson. 


#### Relationship to Binomal Distribution

You may recall the **_Binomial Distribution_** that we learned about previously.  Comparing and contrasting it with the Negative Binomial Distribution helps us better understand what each is used for. 

The **_Binomial Distribution_** describes the number of successes $ k $ achieved in $ n $ trials, where the probability of success is $ p $.

The **_Negative Binomial Distribution_** describes the number of successes $ k $  until observing $ r $ failures (or successes--this is arbitrary, and depends on how you phrase the question; it doesn't particularly matter if we define heads or tails as a failure, as long as we pick one).  Note that these failures do **_not_** need to be consecutive, just cumulative!

#### Putting It Into Words

Let's work through an example of phrasing a problem that would be described by the binomial distribution, and phrasing another problem that would be described by the negative binomial distribution. 

**_Binomial Distribution_**: "I flip a fair coin 5 times. What are the chances that I get heads 0 times? 1 time? 2 times? Etc..."

**_Negative Binomial Distribution_**: I flip a fair coin 5 times. What are the chances it takes me two flips to get heads twice? How about 3 flips to get heads twice? 4 Flips? Etc..."

### Defining Parameters

Now that we know what we know about the Negative Binomial Distribution, let's set some parameters for the coin-flipping experiment we described above and take a look at the corresponding Negative Binomial Distribution that describes it. 

Let's define our problem statement as:

"I'm going to flip a fair coin 10 times. I want to see how long it takes for the coin to land on heads 2 times.  What is the probability that this happens after 2 coin flips? After 3? ... After 10?"

The statement above describes a Negative Binomial Trial. Let's examine it and see if we can find the parameters that we can use to describe the corresponding Negative Binomial Distribution!

$ r = Number\ of\ Failures = 2 $, since we're interested in seeing how long it takes to land on heads a total of two times. 

$ x = Number\ of\ Trials $--this can be any number greater than 2.  It cannot be smaller than 2, because it is mathematically impossible to satisfy our pre-set condition if the number of trials is smaller than our target (it's impossible to get 2 heads out a single coin flip). 

$ p = Fair\ Coin = 0.5$, since a fair coin has a 50/50 chance of landing on either heads or tails. 

The easiest way to think of this is that the distribution has a **_Fixed Number r_** and a **_Random Variable X_**.  When we perform Negative Binomial Trials, we _know how many failures we're looking for_.  This number is denoted as the parameter $r$.  Our random variable is what we don't know--exactly how many trials $x$ it will take to reach our fixed number of failures $r$.    

### The Negative Binomial Formula

If we know the parameters, we can calculate our Negative Binomial Probability by pulling them into the following formula:

$b(x, r, P) =\  _{x-1}C_{\ r-1} * P^{\ r} * (1-P)^{\ x-r}  $ 

Don't worry if this looks pretty overwhelming.  We'll break it down.

Let's start by recalling our parameters:

$ r = 2 $

$ x = 10 $

$ P = 0.5 $ 

You may also be wondering what $_{x-1}C_{\ r-1}$ is the equation.  This is a mathematical notation that stands for $$\frac{(x-1)!}{((n-1)-(r-1))!(r-1)!}$$.  This equation probably looks scary, too, but don't worry--this is just the formula for the binomial distribution, which you've seen before. 

**_A Note on This Equation:_**  This equation is used to calculate the **_Negative Binomial Probability_**, which is just the probability for a given value of $x$, not the entire probability distribution.  If we want to know the Negative Binomial Probability for 10, we set $x=10$ and plug the parameters into this equation. If we want to know the probability for 3, we set $x=3$, and so on. 

#### What Exactly Are We Calculating?

When working with discrete probabilities, it sometimes helps to think of the corresponding trials as a tree diagram. Let's examine all the possible ways that that three coin flips can work out:

We could use our parameters and describe our problem as: What is the negative binomial probability of $b(x=3, r=2, p=0.5)$?

However, we could also phrase it in much more simple terms--what are the odds that we get our 2nd heads on the 3rd coin flip?

Logically, it follows that in order for heads to appear for the 2nd time on the 3rd coin flip, that means that heads must have appeared exactly once by the second trial.  We can generalize this statement further to say that in order for us to hit $r$ on the trial $x$, that means that this can only happen in situations where we have a count of $r-1$ on trial $x-1$.  Another way to phrase is by considering impossibilities at any given step--it's impossible to get our 2nd heads on the third flip if we have 0 heads on the second flip, and also if we had 2 heads on the second flip.  If $r=2$ and $x=3$, then our magic number for step $x=2$ is $r=1$. 

This brings us to that potentially scary equation we saw above. As we mentioned before, the **_Probability Mass Function_** for the **_Binomial Distribution_** hiding inside of that equation. That's one half of the equation above.  The other half of the equation is just calculating the odds that we reach $r$ on trial number $x$.

This means that we can break the equation down into two separate parts:

1. The probability that we have $r-1$ failures on trail $x-1$.  In the negative binomial probability equation, this is denoted by $_{x-1}C_{\ r-1}$.

2. The probability that we get failure $r$ on trial $x$. This is denoted by $P^{\ r} * (1-P)^{\ x-r}$

Since these trials are all independent, we can simply calculate our **_Negative Binomial Probability_** by just multiplying the two, giving us our original equation of:

$$b(x, r, P) =\  _{x-1}C_{\ r-1} * P^{\ r} * (1-P)^{\ x-r} $$

If we use this formula to and plug in the parameter values for our sample problem above, we get the following distribution:

| # Coin Flips | Probability |
|:------------:|:-----------:|
|       2      |     0.25    |
|       3      |     0.25    |
|       4      |    0.1875   |
|       5      |    0.125    |
|       6      |    0.0781   |
|     >= 7     |    0.1094   |


### Characteristics of the Negative Binomial Distribution

The **_mean_** of the Negative Binomial Distribution is: 

$$\mu = \frac{r}{p}$$

The **_variance_** of the Negative Binomial Distribution is:

$$\sigma^2 = \frac{r\ (1-p)}{p^{\ 2}}  $$

### Calculating Negative Binomial Probability with Numpy

Thanks to the wonders of numpy, we can avoid scary functions and calculate Negative Binomial Probabilities with a single line of code. Consider the following example code from the [numpy documenation for negative binomial sampling function](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.negative_binomial.html):

> A company drills wild-cat oil exploration wells, each with an estimated probability of success of 0.1. What is the probability of having one success for each successive well, that is what is the probability of a single success after drilling 5 wells, after 6 wells, etc.?

The following sample code is provided in the documentation to demonstrate how to solve this problem using the `negative_binomial()` function from the `numpy.random` module:

In [28]:
import numpy as np

s = np.random.negative_binomial(1, 0.1, 100000)
for i in range(1, 11):
    probability = sum(s<i) / 1000000
    print(s)
    print(i)
    print(sum(s<i))
    print(probability)
    print("{} wells drilled, probability of success: {:.4f}%".format(i, probability * 100))

[ 0 15  3 ...  2  1  8]
1
10013
0.010013
1 wells drilled, probability of success: 1.0013%
[ 0 15  3 ...  2  1  8]
2
18960
0.01896
2 wells drilled, probability of success: 1.8960%
[ 0 15  3 ...  2  1  8]
3
26989
0.026989
3 wells drilled, probability of success: 2.6989%
[ 0 15  3 ...  2  1  8]
4
34420
0.03442
4 wells drilled, probability of success: 3.4420%
[ 0 15  3 ...  2  1  8]
5
41085
0.041085
5 wells drilled, probability of success: 4.1085%
[ 0 15  3 ...  2  1  8]
6
46983
0.046983
6 wells drilled, probability of success: 4.6983%
[ 0 15  3 ...  2  1  8]
7
52399
0.052399
7 wells drilled, probability of success: 5.2399%
[ 0 15  3 ...  2  1  8]
8
57136
0.057136
8 wells drilled, probability of success: 5.7136%
[ 0 15  3 ...  2  1  8]
9
61384
0.061384
9 wells drilled, probability of success: 6.1384%
[ 0 15  3 ...  2  1  8]
10
65293
0.065293
10 wells drilled, probability of success: 6.5293%


In [33]:
sum(s<1)

10013

In [34]:
sum(s)

895228

In [18]:
14/100000

0.00014

In [29]:
test = 0
for x in range(len(s)):
    if s[x] < 1:
        

0
15
3
15
13
1
2
4
5
19
2
3
4
21
7
7
1
11
4
4
3
1
6
10
25
1
26
5
8
7
7
1
5
3
21
0
20
11
1
10
0
12
12
9
42
16
2
9
3
2
2
12
10
20
11
14
3
7
25
4
5
6
9
4
4
5
12
3
14
2
10
0
3
22
8
12
17
0
2
10
20
3
9
9
32
7
7
0
2
12
6
33
0
3
30
15
3
2
8
1
12
6
0
29
8
16
1
2
3
13
8
16
6
11
0
6
22
12
14
8
12
15
2
4
4
2
25
23
4
1
2
0
1
9
5
6
8
15
8
1
2
4
49
12
1
13
20
7
8
10
16
0
5
3
11
2
28
3
18
3
3
4
3
18
1
0
10
3
3
23
12
30
2
9
12
1
1
36
1
8
1
10
7
10
7
3
16
3
6
12
8
2
8
7
8
15
9
4
15
6
0
8
4
13
0
3
15
1
17
3
3
45
2
2
1
3
6
1
7
2
3
9
1
1
12
6
2
0
4
3
2
7
7
1
9
20
0
0
0
2
2
12
23
41
5
14
21
14
0
1
19
16
2
0
0
8
8
12
0
2
17
0
2
6
1
2
7
7
10
0
0
10
4
3
9
6
21
4
0
4
8
8
18
0
11
0
0
11
46
14
4
23
10
21
0
15
1
9
0
7
3
11
11
19
20
9
7
5
2
6
2
3
3
6
36
0
25
18
14
0
0
10
0
1
5
1
2
9
10
0
8
2
10
31
2
2
15
15
2
3
24
10
0
5
7
13
66
19
15
5
2
19
0
20
13
1
3
26
8
7
21
16
15
18
20
18
17
4
8
3
10
7
3
1
6
15
4
33
2
4
13
7
0
2
0
6
0
12
10
10
21
1
0
11
28
6
7
10
29
0
1
18
5
11
1
2
13
20
7
8
0
22
30
9
0
4
0
40
9
2
5
1
22
1
3

12
0
8
4
1
19
12
13
1
28
20
23
35
24
18
1
42
3
8
0
0
1
3
9
7
2
9
2
6
2
8
24
2
3
13
11
3
6
6
0
1
9
32
19
0
36
5
31
15
1
3
10
15
2
4
4
2
23
1
1
2
4
23
0
2
3
10
13
4
0
3
27
15
3
6
4
12
13
7
11
30
28
6
9
2
2
42
34
7
7
4
16
4
1
4
6
9
3
4
7
4
0
18
14
1
4
0
2
3
13
1
1
3
6
38
11
0
40
2
4
5
10
5
18
1
3
0
5
14
3
2
26
12
11
3
6
5
4
7
7
0
0
22
7
6
12
3
9
0
15
0
34
30
10
10
13
17
6
19
1
10
0
2
7
17
32
18
0
8
9
13
0
8
5
0
1
0
1
6
5
7
61
5
1
1
25
14
5
3
10
0
4
4
17
0
1
1
17
5
19
1
5
2
5
3
6
13
0
5
7
8
31
1
1
26
0
6
5
0
9
3
1
9
8
14
3
16
2
19
14
9
6
9
10
10
5
11
42
9
19
11
17
16
6
5
19
8
1
12
1
4
2
3
16
0
0
21
18
3
7
9
2
18
8
20
11
3
6
8
18
5
27
6
0
2
9
10
0
21
6
4
0
9
0
27
13
3
3
1
13
4
0
3
4
3
34
8
12
22
4
1
5
0
5
4
3
5
19
4
4
1
0
1
3
6
14
0
3
5
0
9
7
3
23
3
6
2
22
9
0
16
7
3
4
9
6
12
22
7
16
3
2
1
6
7
8
12
4
23
4
2
2
5
2
8
2
6
35
42
11
6
11
20
2
7
22
5
22
0
0
0
0
1
2
0
2
11
4
0
2
20
11
3
13
2
6
0
18
7
16
1
6
13
3
1
6
2
5
2
11
7
1
5
2
0
3
8
4
6
5
1
3
0
0
16
1
13
0
40
27
11
19
25
1
35
2
0
29
5
32
11


10
27
3
1
60
12
0
9
1
1
12
30
3
6
4
17
8
0
11
1
2
1
10
49
4
16
6
0
5
6
11
5
0
10
3
2
26
9
19
1
9
11
11
5
12
11
7
15
48
19
3
2
12
12
0
2
11
20
6
8
1
5
7
1
18
1
10
5
4
3
5
5
23
23
5
3
2
8
1
9
4
29
21
4
9
17
0
0
10
5
18
2
10
4
11
10
2
1
9
17
5
15
7
1
16
0
3
1
4
12
3
2
12
22
18
1
8
21
11
2
1
1
3
0
29
11
30
14
6
16
10
2
7
6
17
0
12
29
6
12
12
1
1
7
57
15
13
15
11
17
4
5
9
0
14
4
14
2
26
14
6
4
11
0
6
1
10
18
0
6
18
6
1
1
24
1
14
2
9
11
13
5
4
6
7
0
1
36
1
2
7
3
8
23
15
0
8
9
9
2
7
4
2
0
7
14
12
3
2
9
6
2
5
2
0
2
10
4
2
3
21
23
15
1
0
7
1
5
1
0
6
20
33
1
7
17
0
42
0
2
12
4
13
6
30
8
8
3
26
13
0
34
2
10
1
0
6
11
8
0
3
13
10
6
13
18
8
6
6
14
5
6
5
6
2
9
0
24
0
7
3
12
8
6
8
21
20
21
14
15
1
6
7
11
65
5
3
17
2
1
21
0
7
5
3
10
3
14
5
10
2
24
4
46
1
11
24
2
6
0
5
6
30
1
11
8
24
11
6
1
8
14
9
9
0
1
0
15
5
6
10
9
17
0
18
6
7
2
5
4
2
15
8
2
22
5
5
4
6
31
3
47
5
14
25
24
26
0
5
64
12
1
1
5
46
3
1
24
5
2
21
5
5
17
7
4
20
17
17
0
13
9
7
28
5
6
2
1
1
0
18
4
6
2
3
3
1
19
1
22
7
6
0
2
3
17
3
11
4
12
17
9
6

4
1
2
22
11
12
3
15
38
9
6
30
27
18
5
3
5
4
2
9
6
6
4
3
0
5
2
39
27
15
4
0
4
14
5
7
6
4
9
6
13
1
6
0
6
2
0
9
2
6
1
1
10
6
5
30
2
28
16
1
2
4
27
6
12
0
18
28
5
1
9
9
7
2
22
18
1
1
2
3
11
0
14
2
2
18
5
7
0
17
14
27
10
30
0
6
8
4
3
1
10
4
1
6
16
23
25
0
1
3
10
18
1
16
3
4
30
5
10
2
7
0
7
14
5
28
13
0
10
4
0
6
2
2
8
2
16
13
12
0
5
1
8
4
2
7
9
9
2
2
12
3
12
0
2
19
0
5
7
23
3
2
26
11
11
2
7
3
1
9
5
1
7
6
4
0
9
6
21
16
5
11
3
20
0
9
1
0
15
3
4
36
4
1
13
14
11
1
5
4
13
1
8
7
19
24
2
2
28
4
12
27
0
7
14
0
21
8
44
3
4
7
10
2
5
4
0
0
8
13
16
25
3
0
7
9
0
2
5
20
4
1
4
0
6
4
14
1
2
6
2
0
1
0
5
12
34
21
15
2
22
9
7
5
14
5
3
14
26
12
6
6
0
3
5
1
7
2
0
16
7
11
2
0
7
18
0
9
31
6
14
0
2
41
0
34
8
38
30
3
8
8
1
16
1
4
35
6
5
0
3
0
12
1
15
13
3
11
12
17
2
4
13
5
7
5
2
9
9
1
12
21
3
4
4
5
0
2
4
1
30
21
1
0
12
25
19
7
4
6
4
5
0
15
3
3
2
28
28
12
4
10
30
3
15
1
7
6
11
18
2
2
9
4
8
0
23
3
19
17
9
1
7
3
0
12
22
10
8
8
6
2
1
4
12
13
11
10
7
12
9
1
11
2
5
25
16
6
13
29
15
1
3
9
18
6
3
24
6
16
1
15
2
5
0
2
2
4
6


11
1
7
4
14
18
33
1
9
25
14
1
2
1
6
31
2
5
14
19
4
4
0
9
1
2
13
21
14
12
3
15
33
10
2
22
12
9
2
23
6
21
12
2
1
8
16
7
1
15
16
1
1
6
13
4
36
9
33
35
32
13
9
35
7
25
1
0
2
17
12
1
16
12
18
14
35
1
0
5
16
35
15
3
11
6
21
18
13
9
0
11
33
14
5
5
0
7
3
2
2
6
6
14
1
6
13
14
10
15
2
0
1
6
2
22
1
11
6
5
5
36
1
5
17
12
17
7
4
1
1
7
12
12
7
16
2
4
0
7
23
21
1
7
3
5
3
9
7
13
16
10
6
4
13
3
17
2
7
0
1
17
2
0
11
8
24
3
11
7
15
4
3
0
5
14
6
6
4
1
31
0
3
4
3
28
0
14
4
0
6
21
1
31
0
4
6
7
2
7
5
8
6
1
12
5
15
3
8
1
9
16
0
0
16
16
2
18
9
7
5
27
0
8
22
16
44
7
1
8
18
20
2
3
10
9
4
14
0
9
4
1
9
6
1
10
30
8
3
6
26
9
16
12
11
24
11
4
14
27
19
1
0
7
4
2
0
10
11
2
22
6
26
25
6
2
0
21
1
9
2
25
2
20
19
6
11
8
10
1
8
12
12
14
21
2
9
10
6
10
22
13
3
0
2
18
9
20
21
5
9
6
1
19
6
27
8
3
28
4
2
10
5
12
10
2
2
5
31
21
2
7
3
7
4
2
24
13
10
1
18
8
4
2
16
25
15
30
1
16
2
19
3
6
2
5
15
1
21
8
9
3
18
10
11
0
2
4
4
13
51
14
15
0
5
21
4
3
1
1
1
0
2
5
16
6
7
6
6
5
3
15
2
1
29
4
14
11
8
13
10
17
8
21
0
11
15
8
0
1
5
2
0
1
0
18


6
10
25
9
14
25
2
3
12
0
28
0
2
11
11
5
1
0
35
16
6
6
2
8
3
15
14
10
2
2
23
3
1
18
3
25
25
3
3
3
10
1
32
3
5
1
0
6
7
8
8
3
0
15
0
5
2
2
25
22
1
9
0
1
6
6
3
0
2
2
3
40
25
17
2
1
13
13
17
10
7
5
3
14
0
2
5
50
1
2
1
5
8
3
0
8
6
1
0
28
8
10
14
9
12
4
14
8
10
0
2
23
3
5
12
0
7
14
10
12
2
5
8
1
8
5
20
21
30
9
9
15
1
6
0
0
4
6
0
0
10
0
3
3
1
7
18
23
2
1
12
2
5
1
7
0
10
13
17
20
3
10
1
11
10
7
5
12
0
0
15
7
1
42
2
14
3
10
0
8
20
29
3
17
18
3
7
8
2
6
10
5
14
16
3
10
7
9
2
12
19
28
21
3
2
0
8
0
14
0
16
3
11
5
1
23
32
10
3
17
8
4
6
0
34
0
2
13
2
3
5
17
0
0
17
12
18
0
4
5
15
4
4
5
0
0
5
21
4
0
1
5
5
3
4
21
5
6
8
10
32
17
6
1
9
9
16
1
1
2
1
5
10
4
31
18
2
2
0
10
3
16
12
8
23
18
6
8
5
4
12
2
4
6
23
4
0
6
1
0
4
2
38
6
3
1
1
8
8
6
17
6
7
2
16
10
8
21
5
4
7
0
4
3
0
4
1
15
16
30
20
3
18
0
12
6
2
11
7
34
7
20
1
15
15
9
12
8
9
1
12
18
9
0
0
4
0
1
6
0
31
6
2
7
1
7
17
19
3
17
2
9
7
21
1
4
5
26
16
7
0
23
8
12
15
10
1
3
0
11
8
20
6
16
3
0
16
7
5
27
15
2
5
9
6
2
0
3
0
0
13
19
0
15
5
4
0
1
13
0
1
0
5
3
9
6
20
2

9
3
11
11
7
3
1
2
2
3
6
15
11
2
7
16
3
1
10
8
2
4
13
12
3
3
5
7
6
15
10
6
4
14
9
0
4
4
13
7
5
4
1
15
5
0
5
10
21
14
12
2
3
0
6
7
0
5
15
4
9
2
0
4
0
11
1
0
3
17
10
2
4
6
7
14
19
0
3
15
7
0
5
1
0
12
3
1
1
20
23
2
9
2
2
0
2
6
61
1
8
2
13
4
6
10
12
6
22
8
8
27
3
1
1
13
24
18
2
11
1
13
5
21
4
19
8
0
26
4
1
1
4
2
30
11
1
2
11
6
2
5
19
4
0
1
8
1
4
13
9
0
7
2
0
25
40
6
16
40
23
10
4
1
5
10
4
1
10
11
23
3
2
7
3
35
7
5
3
3
12
2
5
2
3
0
5
19
9
10
23
3
0
7
12
12
2
2
37
7
0
27
0
14
0
27
0
27
7
0
5
21
12
8
25
6
1
19
14
6
10
10
5
0
16
5
5
0
0
8
17
24
32
3
1
1
6
5
0
5
11
19
3
3
7
4
4
1
1
1
22
18
3
5
13
2
13
4
16
21
1
3
2
8
0
9
4
15
4
19
16
1
8
6
4
10
16
4
5
5
5
5
18
14
6
24
28
0
2
22
18
5
0
20
13
23
3
6
3
5
1
26
5
0
14
4
0
3
5
0
1
3
4
1
11
2
19
7
7
6
0
9
24
4
4
36
13
2
9
5
15
3
3
29
2
6
5
18
4
25
11
5
6
28
33
1
0
7
0
6
3
9
13
4
1
4
14
10
15
18
4
0
1
23
5
2
3
2
8
9
8
4
25
1
9
9
9
0
3
26
11
8
1
4
3
11
15
8
5
3
8
1
7
6
3
22
13
17
17
6
13
0
2
3
10
7
12
9
7
21
15
7
15
1
34
3
6
26
11
14
11
2
1
3
50
4
7
0
18

17
7
15
0
0
11
22
5
6
3
0
5
4
27
3
2
9
1
25
4
0
9
21
6
1
1
8
4
43
8
4
3
50
0
0
21
24
10
12
2
7
3
4
6
2
14
10
8
18
12
12
36
14
12
15
36
9
4
13
3
49
1
13
2
0
0
2
13
20
0
0
1
13
17
8
5
27
9
6
11
9
6
25
10
9
11
15
11
4
25
18
3
3
10
1
8
1
11
2
2
4
3
11
9
3
1
10
1
5
16
0
0
19
0
5
20
14
22
0
14
15
23
22
4
4
10
16
1
3
27
13
3
7
5
15
0
9
26
2
14
0
5
34
1
8
12
6
4
2
2
13
5
10
13
2
10
32
17
1
8
0
4
7
20
11
1
4
3
17
3
23
2
0
7
11
13
4
7
35
0
3
40
5
9
17
5
2
21
4
1
27
2
31
10
8
14
7
20
8
4
2
5
2
7
6
3
35
13
2
16
2
6
0
2
3
15
18
6
10
0
4
6
8
7
11
5
3
10
0
39
1
0
9
8
41
6
7
5
2
11
5
5
2
13
6
0
26
2
9
44
0
1
3
10
5
2
3
13
13
1
19
0
9
0
44
38
5
1
0
0
16
11
1
9
0
2
0
1
9
38
12
3
13
0
22
0
0
14
15
4
2
3
10
20
13
3
4
19
8
3
9
7
7
4
16
4
15
12
1
7
1
35
1
26
1
14
6
9
6
0
21
7
1
6
9
9
1
0
20
5
3
0
0
7
18
4
16
3
25
7
9
13
13
3
4
9
1
3
5
0
28
15
11
3
2
8
6
4
5
4
5
7
6
3
1
12
45
1
8
6
8
2
3
0
9
12
14
7
0
1
15
1
6
8
10
1
25
16
6
11
12
4
12
10
3
5
15
10
13
4
7
4
2
23
3
0
7
9
0
22
10
13
2
0
10
3
10
28
16
3
0
9
45


2
10
19
37
11
7
24
2
10
2
4
7
5
14
15
9
0
2
2
0
0
18
2
2
0
9
1
4
9
4
1
1
14
10
9
10
6
31
1
12
12
1
27
1
9
13
5
15
24
43
9
12
5
16
5
5
8
1
0
24
5
6
1
5
5
5
8
27
14
0
14
9
25
0
1
9
2
13
13
8
0
12
0
16
17
0
4
2
4
4
17
21
14
20
15
6
14
8
6
9
9
2
0
5
0
4
0
1
9
20
8
3
3
3
21
2
1
8
12
13
12
22
0
4
6
12
0
5
17
5
5
3
3
4
23
12
9
14
1
11
6
29
7
2
7
10
32
1
7
0
6
2
16
0
2
1
8
4
19
1
10
0
32
14
1
3
6
4
2
3
0
16
1
2
9
19
2
30
10
5
1
6
9
3
20
10
4
6
1
6
0
6
0
7
111
8
7
4
10
7
11
27
4
9
3
4
2
1
6
10
11
11
40
19
2
3
0
2
0
2
0
17
8
14
0
6
38
3
4
2
14
0
3
12
8
1
3
2
13
9
5
6
11
1
7
0
0
4
38
18
3
9
4
5
12
1
5
73
2
8
10
9
8
3
9
15
20
2
20
9
11
5
0
5
5
9
4
5
9
1
6
12
3
10
0
2
9
0
0
2
20
2
4
0
16
12
15
8
35
6
1
10
6
9
2
17
7
1
22
13
6
9
11
1
4
10
11
14
15
10
8
10
8
20
4
5
1
32
3
17
14
2
11
1
21
7
9
54
5
3
5
8
18
25
9
2
2
17
8
3
1
16
6
10
13
4
1
9
10
1
3
13
4
3
18
0
5
9
5
3
20
18
10
0
7
1
3
21
24
11
3
0
13
10
0
1
12
1
1
14
18
0
11
33
3
3
3
16
12
8
2
10
0
22
16
2
0
3
45
16
2
0
7
7
2
4
1
18
2
9
0
8
2
4
4
2
2
0

13
1
23
6
13
10
9
3
7
5
1
0
17
18
3
6
13
16
2
11
29
2
6
0
1
26
11
15
8
0
5
12
15
32
11
12
1
1
8
10
35
12
11
8
4
31
8
5
13
0
9
4
24
1
9
2
2
11
9
4
14
9
12
23
1
25
5
1
6
34
37
33
18
7
13
2
1
30
0
5
0
12
10
2
14
7
13
18
3
10
8
10
1
9
27
29
19
0
5
30
13
2
7
2
0
0
7
6
4
4
0
3
12
14
10
5
5
8
15
7
12
4
14
8
2
7
14
4
15
5
14
6
16
3
6
5
6
2
33
5
5
5
12
1
47
9
6
22
4
0
2
28
3
8
5
8
0
4
25
18
1
5
10
1
8
20
6
12
1
45
2
1
13
3
4
1
3
17
2
25
3
2
10
10
1
1
4
8
7
2
10
22
40
8
1
11
7
19
0
0
4
3
16
26
12
17
2
13
3
13
9
7
3
4
6
1
23
2
1
4
18
5
14
9
5
0
10
15
9
3
5
3
20
0
5
0
8
12
2
6
15
5
5
6
11
0
4
15
8
23
35
6
1
15
40
1
17
11
2
7
10
2
6
29
5
42
6
7
6
8
16
3
2
2
45
25
29
1
1
7
6
2
14
8
2
3
13
2
12
7
34
13
1
6
1
13
1
8
1
10
9
11
21
5
54
17
18
8
13
6
6
10
65
23
12
20
10
14
3
4
6
13
4
0
6
1
6
20
3
19
12
11
6
5
10
25
7
5
4
3
0
4
8
0
1
2
9
6
0
23
35
11
43
29
5
10
24
10
18
2
26
6
1
17
11
1
1
9
0
21
2
1
13
13
4
0
5
8
3
3
17
0
16
3
6
27
6
5
9
9
0
15
0
9
0
0
13
7
3
6
5
3
4
4
3
11
0
11
18
13
3
1
2
8
9
7
22
0
4
14

15
3
10
7
0
0
12
2
2
6
19
16
1
0
5
13
3
0
2
8
11
1
10
3
3
0
4
9
35
0
2
1
11
5
10
1
11
4
7
4
5
12
2
5
0
3
12
7
9
0
6
4
5
15
0
3
14
5
4
9
5
8
1
6
10
6
9
3
3
0
23
0
9
6
0
9
8
5
19
46
14
20
3
3
3
7
5
9
0
3
28
20
2
21
2
8
4
9
8
33
6
23
29
0
2
4
10
3
10
1
14
7
13
5
2
7
0
3
1
4
3
2
7
17
8
1
13
2
12
18
27
0
14
4
13
9
14
15
9
6
6
0
1
1
13
1
1
7
18
18
0
10
24
12
11
0
0
3
0
2
4
10
11
6
1
2
4
7
6
0
4
1
0
11
4
5
7
0
0
4
3
7
18
1
11
18
7
2
17
1
13
1
9
0
9
1
31
1
25
24
13
3
13
4
3
38
9
2
8
1
0
5
1
5
7
1
2
5
6
0
20
15
5
9
3
4
2
4
3
2
4
3
1
11
10
8
2
3
14
2
2
1
6
0
5
0
3
0
13
6
3
14
10
8
5
9
10
1
11
8
7
7
4
6
4
2
1
13
2
28
1
11
50
6
2
3
30
15
28
21
20
11
1
4
10
3
11
9
5
2
0
7
3
3
2
2
30
21
12
26
2
5
10
0
13
10
4
30
15
19
0
10
0
30
3
1
7
0
0
9
30
11
2
0
4
10
2
20
8
33
3
21
11
7
2
7
7
15
13
0
2
17
11
0
6
4
0
17
5
4
26
6
6
4
9
10
8
7
8
1
1
3
0
15
5
2
4
0
12
47
5
0
15
47
6
5
4
2
23
1
5
3
16
2
0
21
6
18
14
5
2
11
2
6
24
3
0
17
0
21
29
3
16
1
7
28
0
14
36
6
43
37
15
0
5
25
1
0
2
0
45
0
4
18
11
26
5
3
12
0
0


24
0
12
1
3
10
21
4
10
38
2
9
16
7
0
3
5
38
1
7
0
14
6
20
15
6
0
4
19
2
0
7
3
35
3
12
12
6
16
41
21
16
7
55
3
0
4
5
4
0
26
16
6
7
2
4
1
7
3
21
5
0
4
9
17
5
3
3
9
22
9
16
1
13
5
1
5
3
2
2
12
8
11
3
1
20
0
2
5
44
10
8
31
1
31
6
17
5
19
4
5
11
3
3
22
5
11
10
0
17
16
12
0
8
17
2
3
16
22
0
0
3
0
20
4
15
3
3
64
7
2
11
6
8
0
0
10
4
10
8
36
12
3
6
28
13
6
12
61
4
1
15
1
16
3
70
9
19
18
11
2
1
3
0
11
12
28
4
5
5
15
3
22
8
1
25
18
12
23
1
6
5
18
4
1
18
13
11
6
5
5
8
0
5
9
8
11
13
3
43
2
11
12
6
3
10
27
13
2
0
0
1
15
0
3
1
1
16
7
3
5
0
11
9
4
10
1
10
3
11
2
9
3
5
9
21
15
13
16
4
3
1
0
26
0
6
2
17
4
10
12
10
3
13
33
8
6
3
3
5
30
1
4
2
8
13
9
7
10
10
12
16
37
9
0
2
7
0
2
7
10
33
36
6
6
18
5
9
0
3
4
12
2
10
25
5
9
2
19
36
18
7
4
10
4
7
4
15
6
1
7
2
17
16
2
4
11
13
12
24
0
40
12
12
6
3
1
1
15
28
4
5
16
6
15
3
13
7
2
2
1
11
20
3
23
0
3
18
5
0
4
3
0
4
0
34
4
31
0
12
8
14
2
14
5
9
3
10
10
0
0
3
21
3
0
6
2
4
2
13
4
7
5
9
0
7
1
1
14
4
5
9
10
29
4
5
35
1
8
16
3
6
19
5
1
7
15
7
24
7
5
20
2
8
34
11
3
1
13
14

11
5
9
5
10
5
0
2
11
5
6
29
3
8
11
4
9
14
3
2
4
1
6
7
11
20
4
11
11
27
9
19
1
7
20
13
10
12
21
21
9
3
10
11
3
7
10
3
1
6
6
4
5
7
5
9
10
3
11
2
0
5
2
3
6
5
1
12
13
12
0
4
1
0
11
1
1
28
4
12
3
17
16
1
34
6
3
19
1
11
9
6
2
2
14
6
0
10
5
13
14
1
4
15
15
5
24
8
8
10
18
2
6
2
26
15
10
4
2
21
10
19
9
9
9
4
0
27
1
2
1
3
1
1
4
32
9
7
0
4
4
2
10
29
10
4
36
0
2
4
34
5
16
0
2
2
23
17
0
17
0
33
5
6
6
2
4
39
2
3
11
11
8
10
6
1
7
18
23
0
4
24
9
11
4
1
7
23
29
7
5
37
12
10
3
7
0
1
1
4
0
11
23
0
1
10
12
2
5
0
4
6
33
6
3
4
11
33
9
11
13
5
0
7
0
9
11
7
7
1
5
16
19
8
26
6
28
2
6
21
10
29
1
5
36
26
2
5
13
1
26
10
22
2
1
35
25
9
10
24
3
2
0
1
0
30
0
9
1
7
17
2
9
19
6
2
3
5
31
11
13
1
31
10
9
6
4
2
4
8
1
3
3
0
2
15
0
20
1
2
3
24
0
7
3
4
7
1
1
1
4
0
12
26
0
5
31
0
4
1
33
9
6
15
5
2
8
8
7
18
14
4
15
2
31
11
3
0
5
0
0
0
2
7
7
4
18
20
3
14
12
6
0
18
3
1
2
7
7
4
10
2
0
27
11
6
1
5
5
1
6
6
1
23
10
9
6
19
1
1
15
11
10
0
2
14
23
11
3
3
1
5
6
20
3
1
5
5
7
5
9
19
67
7
12
21
3
0
0
4
12
3
8
13
0
2
3
5
0
2
12
4
13
5
13
9

6
7
0
1
4
11
31
18
9
14
16
23
6
1
3
8
2
3
5
8
3
3
4
10
6
3
5
5
10
26
1
5
4
3
3
0
42
13
4
21
5
0
6
8
8
18
3
0
3
17
3
3
2
1
8
2
3
0
2
0
14
6
4
3
3
5
0
5
10
13
8
6
17
2
3
10
9
12
28
4
2
4
1
6
2
13
26
2
0
2
0
15
17
2
6
12
7
18
5
4
10
30
1
11
29
8
23
24
13
14
3
4
8
11
9
12
9
0
3
3
20
2
13
0
2
20
20
3
1
20
6
1
21
37
3
18
10
21
4
17
7
29
50
1
7
16
3
6
6
21
4
42
8
23
8
1
8
6
3
4
16
1
2
8
16
2
0
11
0
14
5
19
0
10
3
11
4
15
5
7
0
5
21
6
7
4
6
10
3
8
22
17
6
0
5
11
20
1
13
8
5
15
9
11
54
5
6
2
3
3
10
18
5
3
2
1
1
5
2
6
7
11
5
6
0
17
6
2
2
10
2
8
11
2
6
5
4
13
7
3
2
2
8
7
4
2
5
4
14
2
5
32
7
40
16
12
18
15
3
35
12
38
9
0
1
41
2
2
4
16
5
15
6
13
7
9
2
15
42
28
11
12
5
36
21
7
3
3
11
4
14
0
2
9
21
22
15
6
12
3
11
17
0
0
1
1
0
0
3
20
4
1
1
2
0
3
1
5
1
0
33
1
4
16
14
28
1
5
0
2
2
9
3
3
4
1
3
7
0
5
19
13
1
10
4
8
6
7
11
5
11
1
1
6
5
8
5
11
5
16
19
7
17
1
6
21
4
8
6
6
20
11
28
9
5
3
32
5
5
10
9
3
4
10
1
27
7
0
17
3
3
3
9
4
1
8
11
24
6
1
0
3
7
4
0
2
0
0
20
10
2
12
33
8
6
2
14
0
8
6
0
14
13
9
16
2
0
6
26


12
11
7
6
4
4
4
14
12
4
5
13
5
1
1
11
0
1
0
11
11
4
24
19
2
3
14
11
4
17
14
9
5
6
2
1
8
5
15
30
3
6
3
16
13
32
3
15
5
7
4
0
8
0
4
12
6
7
6
4
10
1
0
14
13
7
16
5
6
8
4
12
9
1
29
7
2
20
14
14
10
3
3
0
5
10
10
5
10
8
25
6
2
7
6
23
2
3
0
2
9
5
23
16
7
5
4
11
32
4
8
0
3
2
5
10
26
18
3
5
4
3
27
9
6
5
3
3
26
21
26
4
33
2
30
12
1
8
5
25
10
11
4
6
4
13
3
0
7
14
18
0
14
9
0
6
14
1
5
6
10
6
6
3
8
16
7
4
3
1
1
13
0
34
3
9
1
8
33
16
15
1
4
11
2
15
0
8
14
0
7
6
9
6
23
1
12
10
7
3
7
1
0
48
15
16
15
0
2
0
1
3
6
1
12
10
14
4
7
3
42
21
0
13
4
46
8
1
7
1
3
9
6
10
1
6
13
3
1
1
3
47
2
8
18
4
33
1
1
7
1
22
9
3
6
11
13
5
4
2
0
11
1
1
1
0
5
1
10
18
4
15
7
0
2
12
13
14
17
0
2
3
2
22
13
15
5
17
8
4
19
0
0
17
14
1
9
9
0
10
3
3
29
8
12
0
17
4
12
5
4
4
3
1
0
0
1
3
3
2
7
5
9
0
5
0
5
73
14
0
24
7
19
14
3
2
6
3
3
7
9
43
7
24
10
5
7
6
1
3
10
3
18
6
26
4
17
0
4
0
21
25
0
4
27
2
14
2
5
0
2
4
9
8
2
3
12
8
6
20
0
4
3
0
3
0
0
7
6
10
2
1
1
0
2
4
18
3
0
15
3
6
0
3
11
3
18
6
5
1
3
46
1
7
13
18
5
0
9
8
2
20
0
22
0
0
12
27
11
0

0
4
9
5
16
23
3
1
8
30
19
1
7
6
1
7
10
6
1
0
19
23
14
3
12
27
0
2
10
1
9
39
32
5
3
1
0
10
9
3
6
0
12
6
0
3
17
4
3
6
13
2
13
24
2
3
6
4
1
40
29
2
0
1
4
19
22
3
6
20
4
0
0
13
9
13
5
3
5
14
0
10
10
10
3
21
0
8
7
11
7
0
29
3
12
1
2
8
2
0
5
3
14
8
31
38
1
1
2
10
4
1
10
7
21
0
10
6
0
10
1
1
22
4
0
2
0
0
37
1
0
10
5
1
6
5
14
19
10
10
7
1
34
9
9
0
2
2
9
13
15
2
7
8
8
5
11
11
6
32
0
1
0
8
2
0
1
8
6
8
1
1
13
0
2
18
3
5
4
4
2
9
21
13
9
3
16
12
22
3
3
4
7
3
3
2
33
0
15
3
1
13
1
1
1
6
20
5
11
17
13
1
4
2
1
19
4
11
4
19
12
3
6
13
12
0
8
2
5
3
1
17
15
0
16
1
0
3
2
5
10
2
19
16
10
20
0
4
12
9
10
22
1
7
3
7
11
21
6
6
0
1
4
10
5
0
12
3
7
26
8
15
4
10
23
1
5
3
7
6
4
30
11
11
10
3
0
2
7
11
16
18
1
18
2
1
5
1
1
5
2
8
2
7
5
6
2
1
22
10
10
4
6
0
1
8
0
9
15
12
2
2
15
4
1
18
65
7
2
0
5
23
19
10
3
8
8
32
1
8
3
10
18
0
4
21
11
32
7
0
2
30
15
25
11
21
16
15
6
1
8
34
2
17
1
2
3
5
4
16
6
1
1
19
0
9
12
4
9
5
3
8
23
8
38
19
3
0
6
7
24
1
29
2
0
7
12
0
3
19
9
1
8
1
12
5
9
7
4
1
4
28
10
11
1
21
3
16
0
1
10
1
17
0
11
0
1

1
28
13
5
0
0
5
0
5
4
2
1
8
9
10
24
5
0
0
6
8
1
15
4
17
17
29
2
3
39
3
3
15
9
35
2
2
26
4
8
4
3
8
4
21
13
3
9
10
3
3
9
0
7
10
0
4
4
0
8
5
6
2
0
9
0
4
22
2
11
21
12
11
4
16
1
4
1
1
27
8
5
1
4
20
13
11
8
15
11
2
16
9
0
12
9
19
0
23
10
5
2
7
14
0
3
7
2
17
8
12
28
5
1
32
0
6
5
3
7
2
31
1
8
6
3
0
43
12
13
25
9
3
3
10
14
6
15
0
0
2
4
22
27
6
14
12
2
2
1
39
1
14
1
5
4
7
0
3
26
17
1
26
3
4
24
2
2
26
1
9
1
5
2
5
21
4
24
17
13
15
10
4
10
0
0
14
2
0
21
8
14
2
5
4
4
4
2
0
2
34
3
7
28
3
6
6
19
3
5
5
3
12
10
2
26
12
13
14
0
12
5
2
4
1
16
7
11
3
0
25
0
1
2
0
6
0
16
6
0
9
14
6
11
0
6
7
37
1
0
5
0
9
8
0
36
0
23
2
5
0
0
3
14
21
14
3
16
11
15
2
16
0
3
2
11
3
14
16
11
0
12
2
0
9
2
5
1
1
1
1
12
28
3
17
4
2
0
10
12
6
13
7
21
14
4
12
13
7
5
5
8
1
32
4
5
21
5
9
1
12
11
0
12
0
8
1
2
1
0
31
8
11
7
7
3
4
4
7
21
5
0
3
36
12
19
3
2
18
19
2
3
36
10
1
15
0
2
1
2
3
0
10
13
5
24
33
5
26
7
25
3
22
13
15
2
1
1
0
19
4
14
9
3
16
5
42
3
9
7
0
4
2
30
4
6
1
6
6
3
14
5
47
23
13
1
2
6
0
1
16
12
2
4
0
6
15
5
4
30
12
1
18
2
7
0


4
22
6
2
8
2
9
9
5
2
1
11
3
1
7
5
4
1
5
14
6
1
9
3
9
10
0
4
1
4
20
15
0
0
9
4
3
7
17
6
0
11
1
1
14
4
11
9
0
38
4
13
0
1
8
0
26
7
7
0
2
11
8
8
21
42
5
1
21
4
43
11
0
20
11
5
11
7
0
3
8
15
5
12
4
6
24
8
0
10
0
3
4
4
7
6
12
1
18
1
8
5
17
31
2
20
13
3
8
2
12
11
19
10
5
1
2
9
5
6
14
1
0
7
15
13
5
23
11
8
24
9
8
22
11
4
3
0
0
1
5
17
2
12
20
13
21
0
10
1
0
8
0
7
23
8
6
2
5
0
14
4
46
0
14
5
10
7
4
9
13
1
1
7
6
1
12
26
10
11
9
11
12
4
0
13
4
5
6
22
13
11
26
47
1
41
9
9
13
23
4
9
7
5
4
50
6
1
4
3
5
30
10
17
5
7
6
24
1
1
6
26
7
14
12
9
2
5
1
16
27
12
4
6
11
14
1
27
10
21
0
5
1
6
1
22
1
4
1
0
5
3
5
9
2
0
6
16
11
1
3
0
3
14
8
5
15
5
0
20
21
2
2
5
13
1
9
2
5
7
17
36
1
9
2
29
4
4
1
2
28
12
0
4
11
24
1
13
15
4
7
7
16
4
9
6
4
37
10
27
7
11
6
37
1
3
1
1
6
9
1
3
7
8
10
0
3
27
0
18
1
5
3
4
15
10
4
0
12
7
2
21
9
10
13
9
9
8
6
10
3
6
19
17
28
0
6
0
14
5
6
0
3
0
8
0
16
1
4
12
5
11
13
8
2
1
5
3
18
18
4
9
0
2
6
14
0
0
16
6
0
1
4
0
7
7
0
3
1
10
3
2
10
24
13
16
2
5
4
34
17
6
57
2
16
9
3
2
8
2
6
1
7
25
5
10
23
5


0
16
13
10
3
25
12
6
2
2
12
8
11
16
7
7
2
19
1
23
3
10
2
8
13
2
10
9
2
9
0
29
4
6
2
19
7
2
36
0
4
1
14
0
6
4
27
13
2
12
1
0
14
33
17
26
17
2
20
1
4
4
0
1
1
1
1
0
3
6
13
4
7
15
6
6
4
13
2
17
0
9
14
8
2
1
5
1
0
2
10
1
1
11
9
9
0
11
3
5
10
4
2
8
8
11
12
17
21
0
4
27
11
13
20
2
9
23
27
10
84
6
9
3
24
10
2
0
3
1
22
17
5
0
4
8
15
12
0
3
0
9
9
9
7
28
0
0
4
4
36
5
11
1
13
1
8
1
2
13
7
25
11
2
11
2
17
19
8
20
5
3
5
12
2
24
0
11
4
3
0
7
20
0
4
8
7
7
3
6
28
15
2
2
6
18
2
16
5
0
15
8
2
0
12
0
27
32
2
14
26
9
1
2
22
1
5
64
16
15
3
3
2
6
32
3
15
5
10
4
65
0
15
51
36
2
6
11
11
9
13
1
36
13
5
7
3
25
27
8
24
20
18
6
6
2
21
8
44
12
1
21
7
4
10
1
3
6
25
11
1
17
20
9
5
13
9
22
0
3
19
3
11
1
10
22
2
1
0
5
0
5
5
13
60
4
15
3
2
3
25
4
0
2
29
18
17
2
0
16
4
2
1
11
7
18
4
5
12
23
18
9
10
19
4
0
0
6
8
0
36
15
14
10
5
10
21
6
6
70
1
0
3
0
5
18
3
1
7
2
0
0
13
6
13
3
65
4
41
7
1
41
48
1
5
10
4
3
3
8
10
1
3
0
35
1
2
9
4
0
46
4
12
15
13
4
0
2
0
20
17
0
7
7
4
2
2
49
7
3
18
7
2
6
0
1
18
3
12
20
4
6
19
2
10
22
14
1
10


2
9
17
12
1
1
5
6
8
1
10
7
12
7
5
9
3
2
4
27
1
8
20
2
25
16
3
11
1
36
1
3
3
21
21
37
27
1
5
0
17
2
1
7
5
6
10
5
0
6
2
12
0
2
16
5
3
5
9
26
37
6
9
6
7
12
7
1
7
11
22
4
13
30
0
2
7
24
34
19
10
1
2
18
0
3
9
10
13
9
0
3
15
1
5
7
25
14
25
1
2
5
6
5
13
3
13
15
7
1
10
9
3
0
4
18
7
24
3
4
14
1
11
21
1
2
5
29
12
2
7
5
2
6
0
6
1
7
2
17
19
5
9
50
11
1
15
15
3
4
0
0
5
5
36
7
5
10
0
1
15
11
6
13
8
39
4
4
23
29
4
3
21
2
7
0
5
4
9
6
17
11
0
15
2
12
12
5
7
2
32
19
13
5
12
11
12
2
4
12
2
8
0
6
7
1
8
0
18
11
42
1
0
18
4
5
7
1
7
13
1
3
29
4
2
10
35
1
1
54
1
0
1
0
5
1
13
11
12
4
10
7
17
4
5
3
0
6
22
9
20
7
10
0
5
2
3
18
5
26
19
12
3
2
23
11
1
24
19
5
8
11
14
42
0
34
0
5
17
13
26
4
3
7
27
2
33
0
12
14
36
6
1
10
7
2
3
4
3
4
2
4
20
1
22
0
3
0
3
7
16
6
3
3
31
11
4
5
1
4
4
3
13
22
3
8
0
0
0
6
0
10
3
0
13
1
3
8
9
0
5
1
24
4
6
17
3
18
34
1
8
3
1
5
7
14
22
2
4
6
11
2
7
5
10
25
4
12
1
9
2
10
15
1
2
1
1
9
5
7
41
8
13
1
2
17
3
0
0
19
23
11
0
3
8
9
8
5
9
0
4
8
9
49
1
3
22
20
21
3
1
2
14
0
1
0
20
9
5
25
1
5
2
11
4
4
1

3
5
0
30
23
7
9
5
9
1
6
14
0
15
7
7
11
12
4
2
23
11
21
10
4
6
18
2
9
15
12
5
7
3
6
13
9
4
5
32
0
4
6
1
6
2
35
2
7
28
1
20
2
22
16
12
9
13
22
13
23
8
1
2
1
1
2
10
7
8
1
11
15
1
3
4
5
7
32
13
0
10
4
11
6
4
2
8
5
1
9
2
0
27
66
0
23
14
4
2
5
3
1
10
7
20
4
21
2
2
29
2
2
2
9
3
6
1
23
1
8
3
19
5
3
0
6
0
2
18
9
6
15
9
1
2
6
12
8
10
8
22
5
7
17
39
18
8
4
17
0
20
7
2
5
10
4
0
0
7
7
5
6
2
5
1
9
4
37
19
4
21
1
1
6
0
4
1
39
0
0
17
5
6
16
7
3
25
11
44
7
22
2
4
20
22
2
39
12
3
1
4
1
0
4
5
0
17
30
3
0
4
8
8
4
3
1
6
25
4
5
1
1
16
13
18
5
4
0
39
2
4
6
0
11
36
19
1
7
1
5
0
12
1
9
3
9
6
25
14
5
7
2
43
7
12
24
15
17
2
4
12
8
1
9
3
0
17
8
0
6
7
1
8
8
7
43
0
4
13
9
4
5
22
2
7
22
10
1
1
4
2
3
1
44
23
5
4
11
5
3
11
40
1
12
9
4
5
12
7
10
10
6
5
26
27
7
2
14
15
11
5
1
10
1
8
4
4
12
13
9
15
8
15
12
4
5
16
1
0
4
8
6
0
1
27
15
2
2
6
13
0
15
4
2
11
27
6
19
3
5
2
2
0
6
13
15
9
0
2
6
0
20
2
2
1
1
5
32
15
10
18
11
0
9
9
10
13
19
8
12
5
10
9
5
9
5
4
4
1
0
0
7
32
26
4
9
17
1
0
0
6
4
12
5
7
9
5
3
8
21
15
2
5
2
2
1
2
1
9
3

19
11
9
2
30
16
50
3
5
5
13
6
22
2
19
14
0
18
6
6
1
3
8
4
15
18
13
6
0
1
0
4
0
25
6
42
8
7
0
2
13
11
6
2
5
15
3
2
1
7
5
19
13
22
2
24
12
2
0
0
10
7
17
3
9
1
1
28
5
5
3
16
0
10
3
8
5
1
12
16
2
6
6
7
19
6
0
11
1
2
16
3
2
6
7
0
12
4
6
1
14
33
9
3
23
10
6
15
0
6
10
3
4
20
1
3
13
7
0
3
8
5
2
7
5
2
4
29
33
4
17
17
7
11
8
11
16
46
10
6
34
0
0
10
5
3
0
30
12
1
3
3
0
17
0
5
4
21
4
12
5
17
9
9
9
9
1
3
2
6
31
11
4
39
16
6
12
11
5
2
6
1
23
4
15
9
5
4
13
6
6
8
4
11
1
4
53
28
1
0
1
1
6
1
5
12
25
2
3
24
6
5
6
1
6
10
22
8
22
0
16
11
1
12
6
7
4
14
4
9
15
15
5
4
3
3
6
0
27
5
13
0
3
16
24
6
0
15
11
17
1
17
12
1
7
9
15
23
2
19
2
4
4
5
2
16
3
0
1
26
4
1
16
2
5
4
16
2
5
42
0
0
0
0
8
7
10
0
1
4
4
2
14
13
1
16
8
4
7
4
3
11
0
6
29
6
2
14
11
2
0
1
4
3
2
6
0
8
12
9
4
0
3
0
4
20
11
3
28
0
13
3
10
19
19
6
2
1
5
32
19
3
23
4
2
2
13
5
9
0
8
1
3
15
8
2
8
5
0
19
5
29
3
12
11
4
4
34
49
0
5
22
9
0
1
1
4
0
5
10
0
2
17
1
1
8
1
4
4
1
13
9
9
10
31
21
15
19
25
0
20
7
3
0
4
2
3
0
10
3
8
10
6
7
13
2
4
8
2
10
4
2
1
6
5
10
1
6
1

## Summary

In this lesson, we learned all about the **_Negative Binomial Distribution_**, as well as related concepts such as **_Negative Binomial Trials_** and **_Negative Binomial Probability_**.  